version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    env_file: .env
    build: ./backend/
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend/
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/backend_static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always