[tool.blue]
line-length = 79

[tool.isort]
profile = "black"
known_django_party = ["foodgram"]
known_local_folder = [""]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'DJANGO_PARTY', 'LOCALFOLDER']
line_length = 79