[tool.blue]
line-length = 79
extend-exclude ='''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
known_django_party = ["foodgram"]
known_local_folder = ["api", "recipes", "users"]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'DJANGO_PARTY', 'LOCALFOLDER']
line_length = 79
skip_glob = ["*/migrations/*.py"]