# Generated by Django 4.2.4 on 2023-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Введите название ингредиента',
                        max_length=200,
                        unique=True,
                        verbose_name='Название ингредиента',
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        help_text='Введите единицу измерения',
                        max_length=200,
                        verbose_name='Единицы измерения',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата публикации'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название рецепта',
                        max_length=200,
                        verbose_name='Название рецепта',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Введите описание рецепта',
                        max_length=3000,
                        verbose_name='Описание рецепта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True,
                        help_text='Введите название тега',
                        max_length=200,
                        unique=True,
                        verbose_name='Название тега',
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        help_text='Введите цвет тега',
                        max_length=7,
                        unique=True,
                        verbose_name='Цвет',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Введите слаг тега',
                        max_length=200,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
