# Generated by Django 4.2.4 on 2023-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe_delete_follow_subscribe_unique_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_user',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='check_author',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='follower',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique_follower'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('follower')), _negated=True), name='check_author'),
        ),
    ]
